### ISSUE TITLE
Liquidbase problem

### ISSUE THREAD

**Issue by netluca1** [tananaev/traccar#2917] opened 2017-02-15 21:28 UTC
i have this problem in the file wrapper.log
```
INFO|1584/0|Service traccar|17-02-15 22:12:38|INFO 2/15/17 10:12 PM: liquibase: Clearing database change log checksums
INFO|1584/0|Service traccar|17-02-15 22:12:38|INFO 2/15/17 10:12 PM: liquibase: Successfully acquired change log lock
INFO|1584/0|Service traccar|17-02-15 22:12:38|INFO 2/15/17 10:12 PM: liquibase: Successfully released change log lock
INFO|1584/0|Service traccar|17-02-15 22:12:38|INFO 2/15/17 10:12 PM: liquibase: Successfully acquired change log lock
INFO|1584/0|Service traccar|17-02-15 22:12:39|INFO 2/15/17 10:12 PM: liquibase: Reading from public.databasechangelog
INFO|1584/0|Service traccar|17-02-15 22:12:39|INFO 2/15/17 10:12 PM: liquibase: Reading from public.databasechangelog
INFO|1584/0|Service traccar|17-02-15 22:12:39|INFO 2/15/17 10:12 PM: liquibase: ./schema/changelog-master.xml: changelog-3.8::changelog-3.8-dropuniquetoken::author: Change set changelog-3.8::changelog-3.8-dropuniquetoken::author failed, but failOnError was false.  Error: ERRORE: il vincolo "uk_user_token" della relazione "users" non esiste [Failed SQL: ALTER TABLE public.users DROP CONSTRAINT uk_user_token]
INFO|1584/0|Service traccar|17-02-15 22:12:39|INFO 2/15/17 10:12 PM: liquibase: Successfully released change log lock
```

**Comment by tananaev** [comment] 2017-02-15 23:00
Please do a search before raising any new issues. Duplicate of #2851.

**Closed by tananaev** 2017-02-15 23:00 UTC
