### ISSUE TITLE
Server dont detect Geofence exit

### ISSUE THREAD

**Issue by vipien** [tananaev/traccar#2282] opened 2016-09-02 22:37 UTC
Install the latest version of traccar, everything seems to work pretty well, except that I found yesterday inside a geofence and my phone with android application traccar I ran out of battery. After a few hours when he was no longer in the same location (I was already outside the geofence) my phone started to report again and connect to the server, but never GeofenceExit event was generated.

When I returned to my work in the morning (that’s where the geofence), and no entry was generated (I guess because the previous day stay) and then Sali, was generated, were two events that were not generated.
```
09/01/2016 1:00 pm (Create the geofence in the application)
09/01/2016 3:00 pm GeofenceEnter (PERFECT)
09/01/2016 4:50 pm (My phone ran out of battery)
09/01/2016 7:00 pm (Charge the battery of my phone again and began to report to traccar server) was not generated geofenceExit
02/09/2016 8:00 a.m. (Come to my office, not generated GeofenceEnter)
```
After began operating here if everything right, because my phone has been with battery

Any explanation for that?

**Comment by tananaev** [comment] 2016-09-03 05:56
Duplicate of the [forum thread](https://www.traccar.org/forums/topic/server-dont-detect-geofence-exit/). Please next time don't duplicate your questions.

**Closed by tananaev** 2016-09-03 05:56 UTC
