### ISSUE TITLE
3.3 and no last position shown on map

### ISSUE THREAD

**Issue by renaudallard** [tananaev/traccar#1646] opened 2016-01-07 15:37 UTC
Hello,

I have freshly installed version 3.3 (So I completely cleared the mysql database from the old data). On former versions 2.x, when I clicked on a device, I could see its latest position highlighted on the map. Also the last position of all devices were shown. Now there is nothing happening when I click on any device. It doesn’t matter whether the device is sending data or not, the only way to see where the device is, is in the reports. Clicking on follow button doesn’t change anything either.

I am running on OpenBSD 5.8 with the following java version:
$ /usr/local/jre-1.8.0/bin/java -version
openjdk version “1.8.0_45”
OpenJDK Runtime Environment (build 1.8.0_45-b14)
OpenJDK 64-Bit Server VM (build 25.45-b02, mixed mode)

Same issue with the following java:
$ /usr/local/jdk-1.7.0/bin/java -version
openjdk version “1.7.0_80”
OpenJDK Runtime Environment (build 1.7.0_80-b15)
OpenJDK 64-Bit Server VM (build 24.80-b11, mixed mode)

**Comment by renaudallard** [comment] 2016-01-07 15:52
I tested both with Firefox 43.0.4 and Chromium Version 47.0.2526.80 Built on 8.2 running on Debian 8.2 (64-bit)

**Comment by tananaev** [comment] 2016-01-07 20:07
Duplicate of the forum thread:

https://www.traccar.org/forums/topic/3-3-and-no-last-position-on-map/

**Closed by tananaev** 2016-01-07 20:07 UTC
