### ISSUE TITLE
Suggest: Add variable response option for GPS103 protocol

### ISSUE THREAD

**Issue by Tucsondirect** [tananaev/traccar#161] opened 2013-03-07 05:30 UTC
Suggest dynamic command that can be stored in database and called during protocol response.

I.e.
custom command is stored in database and when tracker starts negotiation, custom command is parsed from database and passed to tracker.

**Comment by tananaev** [comment] 2015-05-03 23:30
Closing as a dupe of #7.

**Closed by tananaev** 2015-05-03 23:30 UTC
Labels: duplicate
