### ISSUE TITLE
TK116 error

### ISSUE THREAD

**Issue by tawsif93** [tananaev/traccar#3565] opened 2017-10-05 10:49 UTC
I'm using server on my local linux pc with public IP. everything running fine but device connection log showing error.
```
2017-10-05 16:45:54  INFO: [CD1F2F66] connected
2017-10-05 16:45:54  WARN: [CD1F2F66] error - Connection reset by peer - IOException (...)
2017-10-05 16:45:54  INFO: [CD1F2F66] disconnected
2017-10-05 16:45:54  INFO: [4E5288A4] connected
2017-10-05 16:45:54  WARN: [4E5288A4] error - Connection reset by peer - IOException (...)
2017-10-05 16:45:54  INFO: [4E5288A4] disconnected
2017-10-05 16:45:57  INFO: [06F21947] connected
2017-10-05 16:45:57  WARN: [06F21947] error - Connection reset by peer - IOException (...)
2017-10-05 16:45:57  INFO: [06F21947] disconnected
2017-10-05 16:45:59  INFO: [D38F0079] connected
2017-10-05 16:45:59  WARN: [D38F0079] error - Connection reset by peer - IOException (...)
2017-10-05 16:45:59  INFO: [D38F0079] disconnected
2017-10-05 16:46:01  INFO: [40340587] connected
2017-10-05 16:46:01  WARN: [40340587] error - Connection reset by peer - IOException (...)
2017-10-05 16:46:01  INFO: [40340587] disconnected
2017-10-05 16:46:04  INFO: [7E780356] connected
2017-10-05 16:46:04  WARN: [7E780356] error - Connection reset by peer - IOException (...)
2017-10-05 16:46:04  INFO: [7E780356] disconnected
```

**Comment by tananaev** [comment] 2017-10-05 13:20
Duplicate of:

https://www.traccar.org/forums/topic/tk116-gps-device-error/

Please next time don't spam everywhere with same question.

**Closed by tananaev** 2017-10-05 13:20 UTC
