### ISSUE TITLE
No operations allowed after statement closed

### ISSUE THREAD

**Issue by gpsim** [tananaev/traccar#665] opened 2014-04-14 03:51 UTC
Hi, The log file. This why?
```
2014-04-14 11:17:48  WARN: No operations allowed after statement closed. - com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException (null:-1)
```
Another problem, the default MySQL database is ENGINE=MyISAM, excuse me
Engine=innodb and engine=myisam should be what kind of better.

**Comment by motuditli** [comment] 2015-01-25 18:10
Hi, I'd like to followup on this. I have a similar problem.
Situation:
latest traccar installed, mysql configured and working after fresh start or restart.
If there is no activity on the DB (no tracker is sending, no website activity) for more than 8 hours, the connection to the DB fails.
Message:
INFO   | jvm 1    | 2015/01/25 18:10:30 | 2015-01-25 18:10:30.037:WARN:/:Exception while dispatching incoming RPC call
INFO   | jvm 1    | 2015/01/25 18:10:30 | com.google.gwt.user.server.rpc.UnexpectedException: Service method 'public abstract org.traccar.web.shared.model.User org.traccar.web.client.model.DataService.login(java.lang.String,java.lang.String)' threw an unexpected exception: javax.persistence.PersistenceException: org.hibernate.exception.JDBCConnectionException: Communications link failure||The last packet successfully received from the server was 30,612,737 milliseconds ago.  The last packet sent successfully to the server was 9 milliseconds ago.

I already tried a number of things, however I think either the handling of the connection is not clean, or some configuration option is missing.

My current config:
<entry key='database.driver'>com.mysql.jdbc.Driver</entry>
    <entry key='database.dataSource'>com.mysql.jdbc.jdbc2.optional.MysqlConnectionPoolDataSource</entry>
    <entry key='database.url'>jdbc:mysql://127.0.0.1:3306/traccar?allowMultiQueries=true&amp;autoReconnect=true</entry>
    <entry key='database.user'>MY_USER</entry>
    <entry key='database.password'>SOME_PWD</entry>

Any ideas?

**Comment by vitalidze** [comment] 2015-01-25 19:18
I had similar issues and they were fixed by moving to c3p0 connection pool which has a possibility to check connections in pool (see #875). So this happens if some connection to MySQL is opened for a long time without any activity. Try upgrading to traccar 2.10 or 2.11.

**Comment by motuditli** [comment] 2015-01-25 19:31
I am running 2.11.
Do I have to add something to the configuration file, in order to use c3p0? 
After reading the referenced thread my impression is, that this has generically changed since 2.10. 
Sorry, I'm not (yet) so much into Java...

**Comment by vitalidze** [comment] 2015-01-25 19:48
It's always enabled and is testing (and thus warming up) connection every 600 seconds (10 minutes). It's definitely solved this issue in my case. Do you have `c3p0-0.9.2.1.jar` or `c3p0-0.9.5.jar` files under `lib` folder of traccar installation?

**Comment by motuditli** [comment] 2015-01-25 19:55
I have ````c3p0-0.9.5.jar```` under ````lib ````

from what you explain, I would expect also to solve my problem. However it looks like it's not active on my system. 
Since I'm using traccar since > 1 year and had several versions, I will try to cleanup any runtime files and refresh the installation.

I will update as soon as I have news on this. Thanks a lot so far for your support!

**Comment by motuditli** [comment] 2015-01-26 20:06
There is still the issue.

I completely removed the installation directory, made a fresh install, copied the old config-file back and started.
When I tried to login several hours later, again I got:
<pre>
INFO   | jvm 1    | 2015/01/26 20:56:43 | 2015-01-26 20:56:43.103:WARN:/:Exception while dispatching incoming RPC call
INFO   | jvm 1    | 2015/01/26 20:56:43 | com.google.gwt.user.server.rpc.UnexpectedException: Service method 'public abstract org.traccar.web.shared.model.User org.traccar.web.client.model.DataService.login(java.lang.String,java.lang.String)' threw an unexpected exception: javax.persistence.PersistenceException: org.hibernate.exception.JDBCConnectionException: The last packet successfully received from the server was 37,439,808 milliseconds ago.  The last packet sent successfully to the server was 37,439,808 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
</pre>

interestingly the tracker was sending data and those were correctly recorded, so at least here it looks like it is only related to the WebUI.

Any ideas?

**Comment by tananaev** [comment] 2015-01-26 20:11
Web interface uses same data source as the rest of the server. Maybe your MySQL timeout is too short?

**Comment by motuditli** [comment] 2015-01-26 20:16
MySQL wait_timeout is 28800. 
Tracker recording started approx >14h after the start of the server. That should be fine and testing should work for that part.
However, approx. < 2h after the last position sent from the tracker, I tried using the Web-UI and failed with above message.

**Comment by vitalidze** [comment] 2015-01-26 20:19
Can you show your MySQL configuration file? I still see exactly same symptoms that I had with version 2.9 and I have double checked (on two servers) now that it's working fine now.

**Comment by motuditli** [comment] 2015-01-26 20:31
in my.cnf wait_timeout it is not defined, therefore it should be default.
To verify, I checked the runtime values, using "show variables":

<pre>
...
| wait_timeout                                      | 28800
...
</pre>

is there any useful debug I can activate?

**Comment by vitalidze** [comment] 2015-01-27 08:26
You can turn on additional logging for c3p0 in `wrapper.conf`:

````
# Java Additional Parameters
wrapper.java.additional.1=-Dcom.mchange.v2.log.MLog=fallback
wrapper.java.additional.2=-Dcom.mchange.v2.log.FallbackMLog.DEFAULT_CUTOFF_LEVEL=FINE
````

Level `FINE` should has errors appeared on connection testing. You may change it to `ALL` for the most verbose logging. Messages will be printed into latest `wrapper.log.xxxxx` file located under `logs` folder.

**Comment by motuditli** [comment] 2015-01-28 19:58
I implemented the logging change and restarted, so far it looked good:
<pre>
INFO   | jvm 1    | 2015/01/27 09:59:37 | [FINE] Created new pool for auth, username (masked): 'tr******'.
INFO   | jvm 1    | 2015/01/27 09:59:37 | [FINE] awaitAvailable(): [unknown]
</pre>

I almost thought the issue is gone, but now it happened again:
<pre>
INFO   | jvm 1    | 2015/01/28 08:21:56 | [FINE] awaitAvailable(): com.mchange.v2.c3p0.impl.NewPooledConnection@5c4e4be3
INFO   | jvm 1    | 2015/01/28 20:28:16 | [FINE] com.mchange.v2.c3p0.impl.NewPooledConnection@4ecd2597 invalidated by Exception.
INFO   | jvm 1    | 2015/01/28 20:28:16 | com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: The last packet successfully received from the server was 88,014,137 milliseconds ago.  The last packet sent successfully to the server was 88,014,138 milliseconds ago. is longer than the server configured value of 'wait_timeout'. You should consider either expiring and/or testing connection validity before use in your application, increasing the server configured values for client timeouts, or using the Connector/J connection property 'autoReconnect=true' to avoid this problem.
...
INFO   | jvm 1    | 2015/01/28 20:28:16 | [FINE] CONNECTION ERROR OCCURRED!
INFO   | jvm 1    | 2015/01/28 20:28:16 | 2015-01-28 20:28:16.331:WARN:/:Exception while dispatching incoming RPC call
</pre>

Interestingly it states "last packet successfully received from the server was 88,014,137 milliseconds ago" which should be little bit more than 24 hours. 
However, the last position recorded is less than 10 hours ago and also the last web-session was less than 4 hours ago.

Any idea how to proceed?

**Comment by motuditli** [comment] 2015-01-28 20:36
one more observation - maybe it helps...

when checking on the mysql server, I can see three active sessions for the application:
<pre>
mysql> show processlist;
+-----+---------+-----------------+---------+---------+------+-------+------------------+
| Id  | User    | Host            | db      | Command | Time | State | Info             |
+-----+---------+-----------------+---------+---------+------+-------+------------------+
| 134 | tr***** | localhost:54092 | traccar | Sleep   |  367 |       | NULL             |
| 135 | tr***** | localhost:54093 | traccar | Sleep   | 1329 |       | NULL             |
| 136 | tr***** | localhost:54094 | traccar | Sleep   | 2165 |       | NULL             |
| 138 | root    | localhost       | NULL    | Query   |    0 | NULL  | show processlist |
+-----+---------+-----------------+---------+---------+------+-------+------------------+
4 rows in set (0.00 sec)

mysql> 
</pre>

You mentioned before, it should do a refresh of the connection every 10 Minutes. This is true for one connection (in this case id 134). The others don't refresh on it's own. id 135 seems to be associated with the Web-UI (as soon as I login, this connection gets "refreshed"). Id 136 is probably related to the tracker - I have to verify that...

**Comment by vitalidze** [comment] 2015-01-28 22:17
I have no idea on what's happening with your installation. I have done a fresh installation of 2.11 on 32-bit debian "wheezy" linux with MySQL 5.5.40 (installed from repository), OpenJDK 1.7.0_65 and [web UI with my modifications](http://traccar.litvak.su/). All these things are working fine and I don't see any issues with communication links failure. I have multiple warmed up every ten minutes connections:

````
mysql> show full processlist;
+-----+---------+-----------------+---------+---------+------+-------+-----------------------+
| Id  | User    | Host            | db      | Command | Time | State | Info                  |
+-----+---------+-----------------+---------+---------+------+-------+-----------------------+
| 257 | traccar | localhost:48965 | traccar | Sleep   |   69 |       | NULL                  |
| 258 | traccar | localhost:48966 | traccar | Sleep   |  145 |       | NULL                  |
| 262 | traccar | localhost:49517 | traccar | Sleep   |  145 |       | NULL                  |
| 263 | traccar | localhost:49518 | traccar | Sleep   |   23 |       | NULL                  |
| 264 | traccar | localhost:49519 | traccar | Sleep   |  145 |       | NULL                  |
| 265 | traccar | localhost:49523 | traccar | Sleep   |  145 |       | NULL                  |
| 266 | traccar | localhost:49524 | traccar | Sleep   |  145 |       | NULL                  |
| 267 | traccar | localhost:49525 | traccar | Sleep   |  145 |       | NULL                  |
| 272 | traccar | localhost       | traccar | Query   |    0 | NULL  | show full processlist |
+-----+---------+-----------------+---------+---------+------+-------+-----------------------+
9 rows in set (0.00 sec)

mysql> exit
````

Tracker and web UI use same connection pool.

**Comment by motuditli** [comment] 2015-01-29 10:11
there are a number of differences here:
OS: Ubuntu-Server 64 bit
mySQL is the same (5.5.40)
original Sun / Oracle JRE, latest version

I now had a try with your modifications (which I like very much - I will keep it :) ) with the same results, so it's most probably not the code.

I then installed OpenJDK 1.7.0_65, verified that it's actually used, again with the same result.

I somehow doubt, it's related to the OS or mysql. Also the configuration should be fine (I'm using the original config files from the package and only changed the four lines regarding my mysql connection (in traccar.cfg) and your suggested log settings in wrapper.conf

Maybe it's a side effect of the 64bit...

**Comment by motuditli** [comment] 2015-01-29 18:16
one more update:
es describing before, I was able to see the same behavior (connection not refreshed) also with openjdk. After 28800 seconds the (non-refreshing) session was killed from the mysql server.
However, the application did not fail. When I logged into the Web-UI the next time, several new connections were opened and now every(!) connection is being refreshed. 

From what it looks like at this moment, it was probably related to the regular jdk and improving with openjdk.

I will keep an eye on this and update you as soon as I have more details.

One more thing: you people here are really great, very responsive and truly helpful. A very big thank you from my side, especially to vitalidze!!!

**Comment by tananaev** [comment] 2015-01-29 23:30
It sounds like there might be a bug in connection pooling library or the way that we use it.

**Comment by motuditli** [comment] 2015-01-29 23:38
in case you want to dive into it & if you need further input/logs/debugging, I'm happy to assist.

**Comment by tananaev** [comment] 2017-01-15 23:08
Traccar uses different pooling library now. Please reopen if there is still some issue.

**Closed by tananaev** 2017-01-15 23:08 UTC
