### ISSUE TITLE
Netty Warning : Failed to accept a connection 

### ISSUE THREAD

**Issue by mizouzi** [tananaev/traccar#1635] opened 2016-01-02 10:59 UTC
hello,
I've a warning from netty whitch said  'Failed to accept a connection', I've this issue sometimes, without any reason, it appears, and disappears :

![screenshot_43](https://cloud.githubusercontent.com/assets/5320171/12074384/81e7d968-b148-11e5-877c-61db9ae69854.png)

I already add  :
![img1](https://cloud.githubusercontent.com/assets/5320171/12074373/be1ee40e-b147-11e5-8a68-b0838b6d66b1.png)
the  to the configuration file,  but it still  not work.

What could be the cause for this?
Best Regards

**Comment by tananaev** [comment] 2016-01-02 21:32
Usually this error indicates that you've reached a maximum number of connection allowed by operating system. If you are using Linux, there are some configuration parameters you can use to tweak number of allowed connections.

**Comment by mizouzi** [comment] 2016-01-04 10:10
I've not yet reached the maximum number of allowed connections . but I think the old connections remain in CLOSE_WAIT not CLOSED, I think that's the problem

**Comment by tananaev** [comment] 2016-01-04 20:35
The `resetDelay` parameter should help with the problem. How many devices do you have?

**Comment by mizouzi** [comment] 2016-01-05 09:34
As I said before I have already use resetDelay but it still not work, I used more than 1000 divice.

**Comment by tananaev** [comment] 2016-01-05 09:42
How many devices do you have?

**Comment by mizouzi** [comment] 2016-01-05 10:06
more than 1000 divices

**Comment by tananaev** [comment] 2016-01-05 10:09
You know that the limit by default is about 1000 connections on Linux, right? Have you changed it?

**Comment by mizouzi** [comment] 2016-01-05 11:01
I know that the maximum number of allowed connections on LINUX is 1000, and I have 1000 devices, but all those devices didn't connected simultaneously.
The problem is when I check the traccar log file I found that not all the connections are closed. Also in netstat command it shows more than 4000 connections between established and CLOSE_WAIT.

**Comment by tananaev** [comment] 2016-01-05 11:09
If there is no data from device for a `resetDelay` period of time, Traccar server closes connection. What version of Traccar are using by the way?

**Comment by mizouzi** [comment] 2016-01-05 11:37
v2.12

**Comment by tananaev** [comment] 2016-01-05 20:41
That's a very old version. I would recommend to update and see if the problem persists.

**Comment by wahisoufiane** [comment] 2016-02-26 11:37
Hi,

I'm a collegue of mizouzi. The traccar server has been customize very much, so it will be risky to upgrade the version. But I have a question if you had, till 2.12, change something in the closing connection, or exception, or somethings very deep that can avoid this kind of problems?

**Comment by tananaev** [comment] 2016-02-26 21:13
There are two things you need to do to handle high number of connections:

1. Set `resetDelay` parameter to close stale connections

2. Increase OS limit on number of connection for the service

**Comment by wahisoufiane** [comment] 2016-02-27 09:11
If I can explain you a little more about this problem, because it might not be the simple cause of resetDelay, or OS limit.

Everything goes well till a specific time (might be every day), the CLOSE_WAIT began to appear without closing, the .jar process began to take CPU 100 times of before appearing the first CLOSE_WAIT. Then CLOSE_WAIT status began to be more and more till attempting the limit of OS connection. 

So First something is triggering this issue.
Second, even if We increase OS limit, this issue will attempt the limit surely.

Do you think an exception in code not handled could cause that?

**Comment by tananaev** [comment] 2016-02-27 09:45
I think it's the other way around. At some point you reach the limit on connections and everything starts to fail including database connection which probably leads to infinite re-tries and 100% CPU usage.

**Comment by wahisoufiane** [comment] 2016-02-27 09:54
When I remark that the CLOSE_WAIT is triggered, I did a netstat :
```
root@ns3011600:~# netstat -ant | awk '{print $6}' | sort | uniq -c | sort -n
      1 Adresse
      1 établies)
      1 LAST_ACK
      1 SYN_RECV
      2 FIN_WAIT1
      3 TIME_WAIT
     12 LISTEN
     93 ESTABLISHED
    161 CLOSE_WAIT

```
I means that total connection didn't reach 1000 (275 connection in total)
(I have ulimit = 10 000)

Then I found that the CPU is 30% (instead of 5% in normal case)
Then I restart the .jar by kill -9, and restart it. Then every thing goes normal again.
Also when I check the log, I didn't found netty warning.

But If I didn't restart the jar, the CPU will attempt 75%; the connection will attempt limit, the log will show netty warning and then everything starts to fail.

Again, something is triggering this, because before attempting the limit, the CPU began to increase very fast and CLOSE_WAIT also.

**Comment by tananaev** [comment] 2016-02-27 10:33
Limit is set per user. Are you sure you set it for the correct user?

The limit is actually for number of open descriptors which includes files as well, so it is be higher than you see in netstat report.

**Comment by wahisoufiane** [comment] 2016-02-27 11:55
I'm sure it is the same user 'root'.

I did : `ulimit -n 10000` to change the limit.

How can I know the total used files including files and connection to compare it with the ulimit?

**Comment by tananaev** [comment] 2016-02-27 19:33
Please try following command (where pid is Traccar process id):
```
sudo cat /proc/<pid>/limits
```

**Comment by wahisoufiane** [comment] 2016-02-28 21:54
Here is the result :

```
Limit                     Soft Limit           Hard Limit           Units
Max cpu time              unlimited            unlimited            seconds
Max file size             unlimited            unlimited            bytes
Max data size             unlimited            unlimited            bytes
Max stack size            8388608              unlimited            bytes
Max core file size        0                    unlimited            bytes
Max resident set          unlimited            unlimited            bytes
Max processes             257261               257261               processes
Max open files            4096                 4096                 files
Max locked memory         65536                65536                bytes
Max address space         unlimited            unlimited            bytes
Max file locks            unlimited            unlimited            locks
Max pending signals       257261               257261               signals
Max msgqueue size         819200               819200               bytes
Max nice priority         0                    0
Max realtime priority     0                    0
Max realtime timeout      unlimited            unlimited            us
```

**Comment by tananaev** [comment] 2016-02-28 23:39
Looks like the limit for the process is 4096.

**Comment by wahisoufiane** [comment] 2016-03-02 17:21
I was doing some tests this days to prouve that problem is generated before attempting the limit (4096)

First of all, here is a capture of CPU graph line :
![cpu](https://cloud.githubusercontent.com/assets/3135044/13468217/978e3a34-e099-11e5-943c-fe250b636d23.png)

as you can see that after a certain point, CPU used is doubled.

Second, I capture the graph line of file opened by time (blue is the line of process traccar, and red is for the OS):
![fd](https://cloud.githubusercontent.com/assets/3135044/13468282/d3d0c584-e099-11e5-8a46-119e4226067b.png)

As you can see that the problem is generated before attempting any limit of FD (NB: the command used to know the files opened for traccar process is `ls /proc/PID/fd | wc -l`).

Third, I capture the graph line of the close wait status:
![net](https://cloud.githubusercontent.com/assets/3135044/13468343/12dfcc16-e09a-11e5-8072-01108cb7f001.png)

no close_wait state has been stayed open till a certain point, after that all of other connection are not closed too.

We can find also that the time is the same when all the graph line show something wrong.

Finally, I capture the wireshark communication between server and device, and get the ip which is the first one who stay in close_wait status.

![tshark](https://cloud.githubusercontent.com/assets/3135044/13468471/8f40b662-e09a-11e5-842f-56afe7ea2dc4.png)

As we can see, that the server didn't send FIN to the device, but just and ACK to the FIN of the device.

**Comment by tananaev** [comment] 2016-03-02 20:45
TCP protocol is handled by operating system. Traccar doesn't operate at that low level. If you really think there is a problem, it means the problem is with TCP stack in the operating system that you are using.

I think actual problem is in something else. What database are you using? Are you using reverse geocoder?

**Comment by wahisoufiane** [comment] 2016-03-03 00:29
I use ubuntu server 14.04 trusty. I use mysql database and I don't use
reverse geocoder.

**Comment by tananaev** [comment] 2016-03-03 00:37
It might be some problem with the database. Have you tried with default one?

**Comment by wahisoufiane** [comment] 2016-03-03 00:45
What do you mean by default one? How could the problem come from database.
I mean for exemple the record I send you in wireshark who suppose to be the
one who generate the problem is a filtered record in traccar so it has been
persisted.

**Comment by tananaev** [comment] 2016-03-03 00:51
Please read my previous comment carefully. I don't think TCP handling is the problem here.

**Comment by wahisoufiane** [comment] 2016-03-03 09:12
Sorry for my last response I wanted to say that 'the record is filtered in traccar **hasn't** been persisted' witch mean it doesn't reach the database part.

**Comment by tananaev** [comment] 2016-03-03 09:54
How do you know it's this particular message? I don't get that part.

**Comment by wahisoufiane** [comment] 2016-03-03 10:47
As I said in the analyse before, the message I zoom into in the wireshark is the one who has been showed the first CLOSE_WAIT unclosed. Also it is done in the same datetime when every thinks went wrong.

**Comment by tananaev** [comment] 2016-03-03 10:52
It doesn't mean it's the cause and not the result of something else.

**Comment by wahisoufiane** [comment] 2016-03-03 16:08
You are correct in your theory, it is logic. 

But I don't think problem comes from the database for the simple reason that, when the problem occur, all record are decoded and persisted correctly.

Some of the connection after the problem are closed correctly and didn't stay CLOSE_WAIT, but most of them stay CLOSE_WAIT.

If it is not database, what could it be?

**Comment by wahisoufiane** [comment] 2016-03-03 17:39
Maybe something is gonna help us, is that the packet that stay CLOSE_WAIT, didn't log "closing connection by exception/timeout/disconnect", which mean netty doesn't call the close connection.

**Comment by tananaev** [comment] 2016-03-03 21:46
Yes, if the connection is closed, you should see one of those messages in the log.

**Comment by wahisoufiane** [comment] 2016-03-03 21:52
So this is my meaning,  is that netty didn't call close connection. If so ,
why in your opinion?

**Comment by tananaev** [comment] 2016-03-03 22:01
If you don't see corresponding messages in the log, it must be Netty issue.

**Comment by wahisoufiane** [comment] 2016-03-03 22:10
Ok It's weird that no one have facing this problem, knowing that is one of
the essential part of traccar server process. finally i think I will
redirect the issue to netty project. Thank you for your time.

**Comment by tananaev** [comment] 2016-03-03 22:51
Please keep me up to date if you get any updates from Netty project.

**Comment by wahisoufiane** [comment] 2016-03-05 09:41
Hi again,

I did post the issue in netty, still don't have a response. But I have some question that may help this issue : 

Why don't we change this :
`pipeline.addLast("idleHandler", new IdleStateHandler(GlobalTimer.getTimer(), resetDelay, 0, 0));`
by
`pipeline.addLast("idleHandler", new IdleStateHandler(GlobalTimer.getTimer(), resetDelay, 0, resetDelay));`

Would it create a problem? could it resolve something , by closing every connection that is Idle in a certain time?

**Comment by tananaev** [comment] 2016-03-05 11:31
I don't see how it would help with this problem. It would just add write timeout.

**Comment by wahisoufiane** [comment] 2016-03-10 17:16
Hi, 

I did add netty project in traccar so I can add some logs, and I found that timeout Idle are up to resetDelay, and they call fireChannelIdle (to close the connection) but the thread that are responsible of that are not called.

It is like that netty cannot create a thread or that the thread an not runned.

**Comment by tananaev** [comment] 2016-03-10 20:16
Why wouldn't it be able to create threads?

**Comment by wahisoufiane** [comment] 2016-03-10 20:25
I don't know. maybe the thread is created but not running. the sure thing
is that I didn't get the log I should have. Why do you think about that
Anton?

**Comment by tananaev** [comment] 2016-03-10 20:58
Is there any evidence of that? It seems like you are just trying to guess what's happening.

**Comment by wahisoufiane** [comment] 2016-03-10 21:32
Please see my last comment in this link:
https://github.com/netty/netty/issues/4932#issuecomment-194963810

**Comment by tananaev** [comment] 2016-03-10 21:47
There is an `else` case in your code snippet which can be called. How do you know it's not called?

**Comment by wahisoufiane** [comment] 2016-03-10 21:59
Because as I explained that I had a log "TIMEOUT TRIGGERED" correctly wich
means that the TMO is reached and have to call close by timeout. then after
log it will call fireChannelIdle wich will create a thread ( Runnable )
that will call channelIdle who will Log "IDLE FROM ISH" but it doesn't do
it.

**Comment by tananaev** [comment] 2016-03-10 22:24
I see. Then it looks like the event is not delivered to the handler for some reason.

**Comment by wahisoufiane** [comment] 2016-03-14 11:27
Can you explain me why in your new IdleStateHandler, you no more create thread to call channelIdle but you call it directly? should I do the same in 2.12?

**Comment by tananaev** [comment] 2016-03-14 11:35
`IdleStateHandler` is part of Netty library.

**Comment by wahisoufiane** [comment] 2016-03-14 11:48
I'm sorry! you're right! I changed netty library from adding Idle Channel close from call it in a queue to call it directly and the problem wasn't generated again. I'm just afraid if it will cause another problem somewhere else.

**Comment by ankittater** [comment] 2017-01-31 07:35
Hi wahisoufiane , I am facing the same issue how did you fix this? please share.

**Comment by wahisoufiane** [comment] 2017-01-31 09:01
Hi, I'm sorry I didn't close the issue. The main problem of my issue is that the app freeze frome time to time  I forget the exact problem but the solution I found it in the late version of traccar. It is to manage concurrency on getDeviceById:
   

    private final ReadWriteLock devicesLock = new ReentrantReadWriteLock();
    public Device getDeviceByImei(String imei) throws SQLException {
    devicesLock.writeLock().lock();
    try{
        if (devices == null || !devices.containsKey(imei) ||
                (Calendar.getInstance().getTimeInMillis() - devicesLastUpdate.getTimeInMillis() > devicesRefreshDelay)) {
            devices = new HashMap<String, Device>();
            for (Device device : getDevices()) {
                devices.put(device.getImei(), device);
            }
            devicesLastUpdate = Calendar.getInstance();
        } finally {
            devicesLock.writeLock().unlock();
        }

        return devices.get(imei);
    }

**Closed** 2017-01-31 09:15 UTC
