### ISSUE TITLE
Multiple Position GPS103 command

### ISSUE THREAD

**Issue by Jeferex** [tananaev/traccar#156] opened 2013-03-04 15:47 UTC
I wonder if you could add this command to send the device the command to send position every minute. I tell you the issue. When I add one device to traccar, it sends position whenever it wants. But I know a command so the device send position every minute.

The command is: **,imei:359586018966098,C,01m

I think You could add it after "Send response #2".

Is it posible? Thanks in advance.

**Comment by tananaev** [comment] 2015-05-03 23:30
Closing as a dupe of #7.

**Closed by tananaev** 2015-05-03 23:30 UTC
Labels: duplicate
