### ISSUE TITLE
Error when starting the deamon

### ISSUE THREAD

**Issue by rob1968** [tananaev/traccar#1581] opened 2015-12-08 06:59 UTC
Hi,

I get next error when starting the deamon.

——————————–
sudo /opt/traccar/bin/traccar start
Starting traccar…
/opt/traccar/bin/./wrapper: 1: /opt/traccar/bin/./wrapper: Syntax error: “(” unexpected
Waiting for traccar………………
WARNING: traccar may have failed to start.
————————————————-

I’am running a vps with Ubuntu 14.04 LTS 64bit installed.

Who can help to solve this?

Regards,

Rob

**Comment by tananaev** [comment] 2015-12-08 07:28
Duplicate of the forum thread:

https://www.traccar.org/forums/topic/error-starting-deamon-traccar/

**Closed by tananaev** 2015-12-08 07:28 UTC
