### ISSUE TITLE
Feature Request : Delete Positions With a certain Value

### ISSUE THREAD

**Issue by jaimzj** [tananaev/traccar#2474] opened 2016-10-23 18:32 UTC
Dear All,

I am not sure how many of us here would find this feature request useful, but I will still go ahead and list it here,. In-case any or few might up vote this :)

As there is already a feature to disable positions older than x number of days.

I have a scenario where some chinese devices, like TK103, etc. Keeps sending Data with New `fixtime or devicetime` even when the vehicle/device is static/stationary. In such a case even the filter duplicate feature would not work, as it checks for the time.

So to remove such records,. I had been usually running a direct MySQL query to delete all records, which had protocol column a certain value lets say GPS103, and speed value = 0

So for a better option, which can be adapted or used as and how users require, based on device specific data. here is my feature request
1. User can configure columns, and the values it should contain.
2. And the frequency at which this delete option should run.
3. And at that set interval/frequency, the server would check for the position table, specified columns for the set values, and delete them.

I am thinking of using it to clear all junk values, such as GPS Data received when vehicle is stationary. etc.,

**Comment by tananaev** [comment] 2016-10-23 21:50
It sounds too complicated. Can you please be more specific about the positions that you want to remove. You can use filtering by speed and/or distance when vehicle is stationary.

**Comment by renaudallard** [comment] 2016-10-26 05:36
There is a new "static" filter in development version of traccar which filters devices with speed=0. But it's an all or nothing filter.

**Comment by renaudallard** [comment] 2016-10-26 05:44
By the way, if someone calls or texts your device (at least GPS103 ones), it will wake up and try to update its position. This can easily happen with prepaid sim card numbers which have been assigned to someone else in the past.

**Comment by Abyss777** [comment] 2016-10-26 05:46
Also I want to note that (about) zero speed values used to detect trips, if you filter/remove zero speed positions thoughtless, you will probably loose trips functionality in reports.

Best solution is configure device to sleep (do not send positions) while it is not moving.

**Comment by renaudallard** [comment] 2016-10-26 06:00
Abyss777, the problem is that those devices wake up when they receive a phone call or text, even not from the admin number. So even if you tell them to sleep, that won't work if it's a previously assigned number which receives commercial calls or texts all the time. Unless of course, you use the deep sleep functionality of (some of) these devices, which cuts the phone network completely when sleeping.

**Comment by Abyss777** [comment] 2016-10-26 06:08
They should sleep again after call/text.

**Closed** 2017-01-14 14:37 UTC
