### ISSUE TITLE
Send command to device

### ISSUE THREAD

**Issue by robertoalmeida** [tananaev/traccar#365] opened 2013-08-23 17:43 UTC
I implemented the functionality to send the command to the device and would like to know if you want the code to implement.

Initially used protocol suntech.

----

Implementei a funcionalidade de enviar comando ao dispositivo e gostaria de saber se quer o código para implementar.
Inicialmente usei o protocolo suntech.

**Comment by Jeferex** [comment] 2015-04-15 16:58
@robertoalmeida code doesn't work on newer versions. I've tried to do it with no success.

Has anyone updated the code to work on new versions?? If so, please share.

**Comment by tananaev** [comment] 2015-05-03 23:38
Closing as a dupe of #7.

**Closed by tananaev** 2015-05-03 23:38 UTC

**Comment by wnieva** [comment] 2017-03-06 18:19
I need to send engine cut command on a GV200 GPS. I have a table that captures the IMEI and the IP of the GPS but I do not know What is the command to cut engine by means of GPRS ... can someone help me?
Tnk u

**Comment by tananaev** [comment] 2017-03-06 22:31
@wnieva, please don't comment on old closed threads.

**Comment by owaresabd** [comment] 2020-02-27 04:54
could someone send me the code for sending command to coban TK105/B GPS Device?
