### ISSUE TITLE
Address column is empty in the report screen

### ISSUE THREAD

**Issue by tanask** [tananaev/traccar#2643] opened 2016-12-04 21:04 UTC
Why the address column is empty in the report screen
see picture
how ti fill the data on it
Thanx
![address](https://cloud.githubusercontent.com/assets/23650952/20869199/0fa1870e-ba76-11e6-8f61-1d1a9db1c18c.png)

**Comment by tananaev** [comment] 2016-12-04 21:27
Can you please not spam everywhere with essentially the same question. Closing as a dupe of #2642.

**Closed by tananaev** 2016-12-04 21:27 UTC
