### ISSUE TITLE
raspberry pi 3

### ISSUE THREAD

**Issue by oaf2015** [tananaev/traccar#2545] opened 2016-11-17 00:54 UTC
I have forwarder 8082, and 5055 for udp and tcp. I am using my external IP. The testing device from outside the local network is a galaxy s4. It says send failed. What am I doing wrong? I have tried it on raspian jessie pixel, and ubuntu. when I try it on your demo (main one) it works perfect.

**Comment by tananaev** [comment] 2016-11-17 00:59
Please don't create duplicate threads. Closing this one as a dupe of [the forum thread](https://www.traccar.org/forums/topic/raspberry-pi-3/).

**Closed by tananaev** 2016-11-17 00:59 UTC
